module.exports = {
  SET_FACEBOOK_ACCESS_TOKEN: 'SET_FACEBOOK_ACCESS_TOKEN',
  SEARCH_FETCH: 'SEARCH_FETCH',
  SEARCH_RECEIVE: 'SEARCH_RECEIVE',
  SEARCH_SET_QUERY: 'SEARCH_SET_QUERY',
  COURSE_RECEIVE: 'COURSE_RECEIVE',
  COURSE_FETCH: 'COURSE_FETCH',
  COURSE_SET: 'COURSE_SET',
  FORM_RECEIVE: 'FORM_RECEIVE',
  COURSE_RESET: 'COURSE_RESET',
  OFFERING_RECEIVE: 'OFFERING_RECEIVE',
  OFFERING_FETCH: 'OFFERING_FETCH',
  OFFERING_SET: 'OFFERING_SET',
  RECENT_RECEIVE: 'RECENT_RECEIVE',
  RECENT_FETCH: 'RECENT_FETCH',
  RECENT_SET: 'RECENT_SET'
}
