module.exports = {
  SET_FACEBOOK_ACCESS_TOKEN: 'SET_FACEBOOK_ACCESS_TOKEN',
  SEARCH_FETCH: 'SEARCH_FETCH',
  SEARCH_RECEIVE: 'SEARCH_RECEIVE',
  SEARCH_SET_QUERY: 'SEARCH_SET_QUERY',
  COURSE_RECEIVE: 'COURSE_RECEIVE',
  COURSE_FETCH: 'COURSE_FETCH',
  COURSE_SET: 'COURSE_SET'
}
